CREATE VIEW "THD"."THD Distinct Unit Price" AS
SELECT
  "PART#",
  "HOME DEPOT COST",
  "VENDOR COST"
FROM
  "THD"."THDPricingError"
GROUP BY
  "PART#",
  "HOME DEPOT COST",
  "VENDOR COST"
ORDER BY
  "PART#",
  "HOME DEPOT COST",
  "VENDOR COST";